name: Update Nebraska Volleyball Schedule

# Run this workflow every hour
on:
  schedule:
    - cron: '0 * * * *'  # This cron expression means "every hour at minute 0"

jobs:
  update-schedule:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from your repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python 3.9
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      # Step 3: Install dependencies (if any, in case you use requests or BeautifulSoup)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4 requests

      # Step 4: Run the Python script to scrape the data and generate the updated HTML file
      - name: Run scraping script
        run: python new_nebvolleyball_scrape.py

      # Step 5: Commit and push the updated HTML file back to the repository
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add nebraska_volleyball_schedule.html
          git commit -m "Update schedule HTML file"
          git push
